# Generated by Django 2.0.3 on 2018-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_strelka', models.CharField(max_length=200, verbose_name='URL')),
                ('name_card', models.CharField(max_length=20, verbose_name='Имя владельца карты')),
                ('number_card', models.IntegerField(verbose_name='Номер карты')),
            ],
        ),
    ]
