# Generated by Django 2.0.3 on 2018-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strelka', '0002_cart_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number_card',
            field=models.BigIntegerField(verbose_name='Номер карты'),
        ),
    ]
