# Generated by Django 2.0.3 on 2018-03-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strelka', '0011_auto_20180330_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='moneys',
        ),
        migrations.AddField(
            model_name='money',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneys', to='strelka.Cart'),
        ),
    ]
