# Generated by Django 2.0.3 on 2018-04-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strelka', '0014_cart_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='mm',
        ),
        migrations.AddField(
            model_name='cart',
            name='statMoney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strelka.Money'),
        ),
    ]
