# Generated by Django 2.0.3 on 2018-04-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strelka', '0016_auto_20180401_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='statMoney',
        ),
    ]
