# Generated by Django 2.0.3 on 2018-04-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strelka', '0017_remove_money_statmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='statMoney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strelka.Cart'),
        ),
    ]
