# Generated by Django 2.0.3 on 2018-04-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strelka', '0018_money_statmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='statMoney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='strelka.Cart'),
        ),
    ]
