# Generated by Django 2.0.3 on 2018-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strelka', '0019_auto_20180401_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(blank=True, max_length=20, verbose_name='email'),
        ),
    ]
